name: Setup Workspace
description: Setup Node.js, Yarn v4 with Corepack, and install dependencies
inputs:
  build:
    description: 'Whether to run `yarn build` after install'
    required: false
    default: 'false'

runs:
  using: composite
  steps:
    - name: Setup Node.js (no cache)
      uses: actions/setup-node@v3
      with:
        node-version: 22.x

    - name: Enable Corepack
      run: corepack enable
      shell: bash

    - name: Setup Node.js (with Yarn cache)
      uses: actions/setup-node@v3
      with:
        node-version: 22.x
        cache: yarn

    - name: Install dependencies with Yarn
      run: yarn install --frozen-lockfile
      shell: bash

    - name: Build project (optional)
      if: inputs.build == 'true'
      run: yarn build
      shell: bash